/*
PONT - INSERIDO ELEMENTOS EM UM VETOR

FAÇA UM PROGRAMA QUE LEIA INICIALMENTE O TAMANHO N DE UM VETOR DE INTEIROS

DEPOIS, O PROGRAMA DEVE ALOCAR DINAMICAMENTE UM VETOR DE N POSIÇÕES.

EM SEGUIDA, O PROGRAMA DEVE LER N NÚMEROS INTEIROS E OS INSERI-LOS NO VETOR, USANDO UM SEGUNDO
PONTEIRO PARA ESTA TAREFA: SE O VETOR É V, E O PONTEIRO É P, VOCÊ DEVE USAR P PARA APONTAR PARA A POSIÇÃO
---- DO VETOR, E USAR ESTE PONTEIRO PARA INSERIR O ELEMENTO NO VETOR.

FINALMENTE, VARRA O VETOR USANDO UM PONTEIRO, E MOSTRE O SEU CONTEÚDO.

ENTRADA: A ENTRADA CONSISTE DE 2 LINHAS:
*/