/*
PONT - ELEMENTOS PARES E POSITIVOS DE UM VETOR

FAÇA UM PROGRAMA QUE LEIA INICIALMENTE O TAMANHO N DE UM VETOR DE INTEIROS

DEPOIS, O PROGRAMA DEVE LER N NÚMEROS INTEIROS E OS INSERI-LOS NO VETOR

FINALMENTE, VARRA O VETOR USANDO UM PONTEIRO, E DETERMINE QUANTOS ELEMENTOS SÃO PARES E POSITIVOS.

ENTRADA: A ENTRADA CONSISTE DE 2 LINHAS:
- A PRIMEIRA LINHA CONTÉM APENAS UM INTEIRO N, QUE CORRESPONDE AO TAMANHO DO VETOR.
- NA SEGUNDA LINHA, TEM-SE N INTEIROS, SEPARADOS POR UM ESPAÇO EM BRANCO.

SAÍDA:
*/