/*
PONT - MÉDIA DOS ELEMENTOS DE UM VETOR

FAÇA UM PROGRAMA QUE LEIA INICIALMENTE O TAMANHO N DE UM VETOR DE INTEIROS.

DEPOIS, O PROGRAMA DEVE LER N NÚMEROS INTEIROS E OS INSERI-LOS NO VETOR.

FINALMENTE, VARRA O VETOR USANDO UM PONTEIRO, E CALCULE A MÉDIA DOS ELEMENTOS DESTE VETOR.

ENTRADA: A ENTRADA CONSISTE DE 2 LINHAS:
- A PRIMEIRA CONTÉM APENAS UM INTEIRO N, QUE CORRESPONDE AO TAMANHO DE VETOR.
- NA SEGUNDA LINHA, TEM-SE N INTEIROS, SEPARAFOS POR UM ESPAÇO EM BRANCO.

SAÍDA:
*/