/*
PONT - MAIOR ELEMENTO DE UM VETOR

FAÇA UM PROGRAMA QUE LEIA INICIALMENTE O TAMANHO DE N DE UM VETOR DE INTEIROS.

DEPOIS, O PROGRAMA DEVE LER N NÚMEROS INTEIROS E OS INSERI-LOS NO VETOR.

FINALMENTE, VARRA O VETOR USANDO UM PONTEIRO, E RETORNE O MAIOR ELEMENTO DESTE VETOR.

ENTRADA: A ENTRADA CONSISTE DE 2 LINHAS:
- A PRIMEIRA LINHA CONTÉM APENAS UM INTEIROS N, QUE CORRESPONDE AO TAMANHO DO VETOR.
- NA SEGUNDA LINHA, TEM-SE N INTEIROS, SEPARADOS POR UM ESPAÇO EM BRANCO.

SAÍDA:
*/