/*
LIST - PROCURAR NA LISTA

FAÇA UMA FUNÇÃO QUE RECEBA EM SUA ENTRADA UM PONTEIRO PARA UMA LISTA LIGADA QUE ARMAZENA NÚMEROS INTEIROS, E UM 
NÚMERO INTEIRO, E RETORNE TRUE SE ESTE ESTIVER NA LISTA, E FALSE CASO CONTRÁRIO. O CABEÇALHO DESTA FUNÇÃO DEVE SER:

BOOL ENCONTRAR(LIST<INT> LISTA, INT X)

DEPOIS, FAÇA UM PROGRAMA QUE VÁ LENDO VÁRIOS NÚMEROS E OS INSERINDO NA LISTA, E EM SEGUIDA LEIA O NÚMERO A SER 
PESQUISADO. ESTE DEVE MOSTRAR A MENSAGEM "ENCONTRADO", SE O NÚMERO A SER PESQUISADO ESTIVER NA LISTA, E "NAO 
ENCONTRADO", CASO CONTRÁRIO

ENTRADA: A ENTRADA CONSISTE DUAS LINHAS.
A PRIMEIRA CONTÉM VÁRIOS NÚMEROS INTEIROS, QUE DEVEM SER COLOCADOS NA LISTA. O FINAL DESTA LINHA É SINALIZADO PELO NÚMERO 0, QUE NÃO DEVE SER INSERIDO NA LISTA.
A SEGUNDA LINHA CONTÉM APENAS UM INTEIRO N, QUE É O NÚMERO A SER PESQUISADO NA LISTA
*/