/*
LIST - SUPERMERCADO

UM GERENTE DE SUPERMERCADO POSSUI DUAS LISTAS, SENDO A PRIMEIRA COM OS CÓDIGOS DE PRODUTOS QUE ESTÃO NO ESTOQUE, 
E A SEGUNDA COM OS CÓDIGOS DOS PRODUTOS QUE JÁ ESTÃO DISPONÍVEIS PARA VENDA.

SEMPRE QUE UM PRODUTO NOVO CHEGA, PRIMEIRO ELE É ADICIONADO NO ESTOQUE, E DEPOIS É MOVIDO PARA VENDA, À MEDIDA 
EM QUE OS PRODUTOS VÃO SENDO VENDIDOS.

ELE PRECISA DE ALGUÉM PARA GERENCIAR ESSAS LISTAS E CONTRATOU VOCÊ PARA O SERVIÇO.

ENTRADA: A PRIMEIRA LINHA CONTÉM UM ÚNICO INTEIRO N, QUE CORRESPONDE AO NÚMERO DE OPERAÇÕES.
DEPOIS SEGUEM-SE N LINHAS, SENDO QUE CADA LINHA CORRESPONDE A UMA OPERAÇÃO.
SE O PRIMEIRO NÚMERO DA LINHA FOR 1, VOCÊ DEVERÁ LER O CÓDIGO DO PRODUTO E COLOCÁ-LO NO ESTOQUE;
SE FOR 2, VOCÊ DEVERÁ PEGAR UM ELEMENTO DO ESTOQUE E COLOCÁ-LO PARA VENDA.

SAÍDA: A SAÍDA DEVERÁ MOSTRAR QUAIS ELEMENTOS ESTÃO NO ESTOQUE E QUAIS ESTÃO DISPONÍVEIS PARA VENDA.
*/