/*
LIST - SOMA DOS NÓS

FAÇA UMA FUNÇÃO QUE RECEBA EM SUA ENTRADA UM PONTEIRO PARA UMA LISTA LIGADA, E RETORNE A SOMA DOS NÓS NESTA LISTA.
O CABEÇALHO DESTA FUNÇÃO DEVE SER:

INT SOMA(LIST<INT> LISTA)

DEPOIS, FAÇA UM PROGRAMA QUE VÁ LENDO VÁRIOS NÚMEROS E OS INSERINDO NA LISTA, E EM SEGUIDA MOSTRE A SOMA DOS NÓS 
DESTA LISTA.

ENTRADA: A ENTRADA CONSISTE VÁRIOS NÚMEROS INTEIROS, QUE DEVEM SER COLOCADOS NA LISTA. O FINAL DA ENTRADA É SINALIZADO 
PELO NÚMERO 0, QUE NÃO DEVE SER INSERIDO NA LISTA.

SAÍDA: NA SAÍDA, O PROGRAMA DEVE MOSTRAR A SOMA DOS NÓS QUE FORAM INSERIDOS NA LISTA.
*/