/*
LIST - CONTAR NÓS

FAÇA UMA FUNÇÃO QUE RECEBA EM SUA ENTRADA UM PONTEIRO PARA UMA LISTA LIGADA, E RETORNE O NÚMERO DE NÓS NESTA LISTA.
ESTA FUNÇÃO DEVE TER O SEGUINTE CABEÇALHO:

INT CONTAR(LIST<INT> LISTA)

DEPOIS, FAÇA UM PROGRAMA QUE VÁ LENDO VÁRIOS NÚMEROS E OS INSERINDO NA LISTA, E EM SEGUIDA MOSTRE O NÚMERO DE NÓS 
DESTA LISTA.

ENTRADA: A ENTRADA CONSISTE VÁRIOS NÚMEROS INTEIROS, QUE DEVEM SER COLOCADOS NA LISTA. O FINAL DA ENTRADA É SINALIZADO PELO 
NÚMERO 0, QUE NÃO DEVE SER INSERIDO NA LISTA.

SAÍDA: NA SAÍDA, O PROGRAMA DEVE MOSTRAR O NÚMERO DE NÓS QUE FORAM INSERIDOS NA LISTA.
*/