/*
LIST - UNIÃO

FAÇA UM PROGRAMA QUE LEIA OS DADOS DE DUAS LISTAS LIGADAS CUJOS ELEMENTOS ESTÃO EM ORDEM CRESCENTE, CRIE E MOSTRE 
UMA TERCEIRA LISTA LIGADA, FORMADA PELA UNIÃO DOS ELEMENTOS DAS DUAS LISTAS ORIGINAIS, TAMBÉM ORDENADA EM ORDEM 
CRESCENTE.

ENTRADA: A ENTRADA CONSISTE DUAS LINHAS:
- A PRIMEIRA CONTÉM VÁRIOS NÚMEROS INTEIROS, QUE DEVEM SER COLOCADOS NA LISTA 1. O FINAL DESTA LINHA É SINALIZADO PELO
NÚMERO 0, QUE NÃO DEVE SER INSERIDO NA LISTA 1.
- A SEGUNDA TAMBÉM CONTÉM VÁRIOS NÚMEROS INTEIROS, QUE DEVEM SER COLOCADOS NA LISTA 2. O FINAL DESTA LINHA É 
SINALIZADO PELO NÚMERO 0, QUE NÃO DEVE SER INSERIDO NA LISTA 2.

SAÍDA: NA SAÍDA, O PROGRAMA DEVE MOSTRAR OS ELEMENTOS DA LISTA 3, FORMADA PELA UNIÃO DOS ELEMENTOS DAS DUAS LISTAS, 
ORDENADOS EM ORDEM CRESCENTE.
*/