/*
LIST - FILA

FAÇA UM PROGRAMA QUE LEIA 4 VALORES INTEIROS E OS INSIRA NO FINAL DE UMA LISTA LIGADA (VEJA QUE ESTAMOS IMPLEMENTANDO
UMA FILA).

DEPOIS O PROGRAMA DEVE IR REMOVENDO OS ELEMENTOS DA LISTA E MOSTRANDO-OS NA TELA.

ENTRADA: A ENTRADA CONSISTE DE 4 NÚMEROS INTEIROS
SAÍDA: NA SAÍDA, O PROGRAMA DEVE MOSTRAR OS ELEMENTOS INSERIDOS.
*/