/*
LIST - PILHA

FAÇA UM PROGRAMA QUE LEIA 4 VALORES INTEIROS E OS INSIRA EM UMA PILHA. DEPOIS O PROGRAMA DEVE IR REMOVENDO OS
ELEMENTOS DA PILHA E MOSTRANDO-OS NA TELA.

ENTRADA: A ENTRADA CONSISTE EM 4 NÚMEROS INTEIROS
SAÍDA: NA SAÍDA, O PROGRAMA DEVE MOSTRAR OS ELEMENTOS INSERIDOS.
*/